package request;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-08-12T06:34:44.910-06:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://localhost/LunchService", name = "LunchService")
@XmlSeeAlso({ObjectFactory.class})
public interface LunchService {

    @RequestWrapper(localName = "order", targetNamespace = "http://localhost/LunchService", className = "request.Order")
    @WebMethod
    @ResponseWrapper(localName = "orderResponse", targetNamespace = "http://localhost/LunchService", className = "request.OrderResponse")
    public void order(
        @WebParam(name = "Restaurant", targetNamespace = "")
        java.lang.String restaurant,
        @WebParam(name = "item", targetNamespace = "")
        java.lang.String item
    );

    @WebResult(name = "RestaurantList", targetNamespace = "")
    @RequestWrapper(localName = "getRestaurants", targetNamespace = "http://localhost/LunchService", className = "request.GetRestaurants")
    @WebMethod
    @ResponseWrapper(localName = "getRestaurantsResponse", targetNamespace = "http://localhost/LunchService", className = "request.GetRestaurantsResponse")
    public java.util.List<request.GetRestaurantsResponse.RestaurantList> getRestaurants();
}
