
package request;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-08-12T06:34:44.839-06:00
 * Generated source version: 2.7.6
 * 
 */
public final class LunchService_LunchServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service/", "LunchService");

    private LunchService_LunchServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = LunchService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        LunchService_Service ss = new LunchService_Service(wsdlURL, SERVICE_NAME);
        LunchService port = ss.getLunchServiceImplPort();  
        
        {
        System.out.println("Invoking order...");
        java.lang.String _order_restaurant = "";
        java.lang.String _order_item = "";
        port.order(_order_restaurant, _order_item);


        }
        {
        System.out.println("Invoking getRestaurants...");
        java.util.List<request.GetRestaurantsResponse.RestaurantList> _getRestaurants__return = port.getRestaurants();
        System.out.println("getRestaurants.result=" + _getRestaurants__return);


        }

        System.exit(0);
    }

}
