//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.30 at 07:38:01 PM MDT 
//


package servlets;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the servlets package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: servlets
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Service }
     * 
     */
    public Service createService() {
        return new Service();
    }

    /**
     * Create an instance of {@link Service.Restaurant }
     * 
     */
    public Service.Restaurant createServiceRestaurant() {
        return new Service.Restaurant();
    }

    /**
     * Create an instance of {@link Service.Restaurant.Menu }
     * 
     */
    public Service.Restaurant.Menu createServiceRestaurantMenu() {
        return new Service.Restaurant.Menu();
    }

    /**
     * Create an instance of {@link Service.Restaurant.Menu.Item }
     * 
     */
    public Service.Restaurant.Menu.Item createServiceRestaurantMenuItem() {
        return new Service.Restaurant.Menu.Item();
    }

}
