//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.30 at 07:38:01 PM MDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/restaurants", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package servlets;
